CREATE EXTENSION IF NOT EXISTS PGCRYPTO;

CREATE TABLE IF NOT EXISTS PUBLIC.POKER_TABLES (
  ROOM_CODE TEXT PRIMARY KEY,
  STATE JSONB NOT NULL,
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE PUBLIC.POKER_TABLES ENABLE ROW LEVEL SECURITY;

DO $$

BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'poker_tables'
      AND POLICYNAME = 'public_read_poker_tables'
  ) THEN
    CREATE POLICY PUBLIC_READ_POKER_TABLES ON PUBLIC.POKER_TABLES FOR
    SELECT
      TO ANON,
      AUTHENTICATED
      USING (TRUE);
  END IF;
END $$;
 

-- Blackjack tables
CREATE TABLE IF NOT EXISTS PUBLIC.BLACKJACK_TABLES ( ROOM_CODE TEXT PRIMARY KEY, STATE JSONB NOT NULL, UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() );
ALTER TABLE PUBLIC.BLACKJACK_TABLES ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'blackjack_tables'
      AND POLICYNAME = 'public_read_blackjack_tables'
  ) THEN
    CREATE POLICY PUBLIC_READ_BLACKJACK_TABLES ON PUBLIC.BLACKJACK_TABLES FOR
    SELECT
      TO ANON,
      AUTHENTICATED
      USING (TRUE);
  END IF;
END $$;
 

-- Player chip balances - universal system for poker and blackjack
CREATE TABLE IF NOT EXISTS PUBLIC.PLAYER_CHIPS ( ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(), SESSION_ID TEXT NOT NULL, GAME_TYPE TEXT NOT NULL, ROOM_CODE TEXT NOT NULL, CHIP_BALANCE INTEGER NOT NULL DEFAULT 1000, BUY_IN_AMOUNT INTEGER NOT NULL DEFAULT 1000, TOTAL_BUY_INS INTEGER NOT NULL DEFAULT 1, JOINED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(SESSION_ID, ROOM_CODE, GAME_TYPE) );
ALTER TABLE PUBLIC.PLAYER_CHIPS ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'player_chips'
      AND POLICYNAME = 'public_read_player_chips'
  ) THEN
    CREATE POLICY PUBLIC_READ_PLAYER_CHIPS ON PUBLIC.PLAYER_CHIPS FOR
    SELECT
      TO ANON,
      AUTHENTICATED
      USING (TRUE);
  END IF;
END $$;
 

-- Lobbies view for faster querying
CREATE TABLE IF NOT EXISTS PUBLIC.GAME_LOBBIES ( ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(), ROOM_CODE TEXT NOT NULL UNIQUE, GAME_TYPE TEXT NOT NULL, HOST_NAME TEXT NOT NULL, PLAYER_COUNT INTEGER NOT NULL DEFAULT 0, HAND_NUMBER INTEGER NOT NULL DEFAULT 1, PHASE TEXT NOT NULL, CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() );
ALTER TABLE PUBLIC.GAME_LOBBIES ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'game_lobbies'
      AND POLICYNAME = 'public_read_game_lobbies'
  ) THEN
    CREATE POLICY PUBLIC_READ_GAME_LOBBIES ON PUBLIC.GAME_LOBBIES FOR
    SELECT
      TO ANON,
      AUTHENTICATED
      USING (TRUE);
  END IF;
END $$;
 

-- User Wallets - persistent chip storage
CREATE TABLE IF NOT EXISTS PUBLIC.USER_WALLETS ( ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(), USER_ID UUID NOT NULL UNIQUE REFERENCES AUTH.USERS(ID) ON DELETE CASCADE, SESSION_ID TEXT, DISPLAY_NAME TEXT NOT NULL, WALLET_BALANCE INTEGER NOT NULL DEFAULT 10000, TOTAL_DEPOSITED INTEGER NOT NULL DEFAULT 10000, TOTAL_WITHDRAWN INTEGER NOT NULL DEFAULT 0, CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() );
ALTER TABLE PUBLIC.USER_WALLETS ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'user_wallets'
      AND POLICYNAME = 'user_wallets_select_own'
  ) THEN
    CREATE POLICY user_wallets_select_own ON public.user_wallets FOR
    SELECT
      TO AUTHENTICATED
      USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'user_wallets'
      AND POLICYNAME = 'user_wallets_insert_own'
  ) THEN
    CREATE POLICY user_wallets_insert_own ON public.user_wallets FOR INSERT TO AUTHENTICATED WITH CHECK (
      auth.uid() = user_id
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'user_wallets'
      AND POLICYNAME = 'user_wallets_update_own'
  ) THEN
    CREATE POLICY user_wallets_update_own ON public.user_wallets FOR
    UPDATE TO AUTHENTICATED USING (
      auth.uid() = user_id
    ) WITH CHECK (
      auth.uid() = user_id
    );
  END IF;
END $$;
 

-- Wallet Transactions - audit log
CREATE TABLE IF NOT EXISTS PUBLIC.WALLET_TRANSACTIONS ( ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(), USER_ID UUID NOT NULL REFERENCES AUTH.USERS(ID) ON DELETE CASCADE, SESSION_ID TEXT, TRANSACTION_TYPE TEXT NOT NULL, GAME_TYPE TEXT NOT NULL, ROOM_CODE TEXT NOT NULL, AMOUNT INTEGER NOT NULL, BALANCE_BEFORE INTEGER NOT NULL, BALANCE_AFTER INTEGER NOT NULL, DESCRIPTION TEXT NOT NULL, CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() );
ALTER TABLE PUBLIC.WALLET_TRANSACTIONS ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'wallet_transactions'
      AND POLICYNAME = 'wallet_transactions_select_own'
  ) THEN
    CREATE POLICY wallet_transactions_select_own ON public.wallet_transactions FOR
    SELECT
      TO AUTHENTICATED
      USING (auth.uid() = user_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'wallet_transactions'
      AND POLICYNAME = 'wallet_transactions_insert_own'
  ) THEN
    CREATE POLICY wallet_transactions_insert_own ON public.wallet_transactions FOR INSERT TO AUTHENTICATED WITH CHECK (
      auth.uid() = user_id
    );
  END IF;
END $$;
 

-- Writes are handled by Next.js API routes via service role key.
-- User Profiles - public profile information
CREATE TABLE IF NOT EXISTS PUBLIC.USER_PROFILES ( ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(), USER_ID UUID NOT NULL UNIQUE REFERENCES AUTH.USERS(ID) ON DELETE CASCADE, DISPLAY_NAME TEXT NOT NULL, AVATAR_URL TEXT, BIO TEXT, TOTAL_GAMES_PLAYED INTEGER NOT NULL DEFAULT 0, TOTAL_WINNINGS INTEGER NOT NULL DEFAULT 0, CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(), UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW() );
ALTER TABLE PUBLIC.USER_PROFILES ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'user_profiles'
      AND POLICYNAME = 'user_profiles_public_read'
  ) THEN
    CREATE POLICY user_profiles_public_read ON public.user_profiles FOR
    SELECT
      TO ANON,
      AUTHENTICATED
      USING (TRUE);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      PG_POLICIES
    WHERE
      SCHEMANAME = 'public'
      AND TABLENAME = 'user_profiles'
      AND POLICYNAME = 'user_profiles_update_own'
  ) THEN
    CREATE POLICY user_profiles_update_own ON public.user_profiles FOR
    UPDATE TO AUTHENTICATED USING (
      auth.uid() = user_id
    ) WITH CHECK (
      auth.uid() = user_id
    );
  END IF;
END $$;